
app = ""
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "vaultwarden/server@sha256:7011d4216a00fcd79785b8b31d61b897e05d959aa37681323dd9c0155655bbbc"

[env]
  DOMAIN = "https://<your proxy app name>.fly.dev"
  IP_HEADER = "X-Forwarded-For"
  I_REALLY_WANT_VOLATILE_STORAGE = "true"
  ORG_ATTACHMENT_LIMIT = "0"
  ORG_CREATION_USERS = "none"
  ROCKET_ADDRESS = "::"
  ROCKET_PORT = "8080"
  SENDS_ALLOWED = "f"
  SIGNUPS_ALLOWED = "f"
  USER_ATTACHMENT_LIMIT = "0"
  WEBSOCKET_ADDRESS = "::"
  WEBSOCKET_ENABLED = "true"
  WEB_VAULT_ENABLED = "f"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []
  private_network = true

[[mounts]]
  destination = "/data"
  encrypted = true
  processes = []
  source = "vaultwarden"

[[services]]
  http_checks = []
  internal_port = 8080
  ports = []
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[services]]
  http_checks = []
  internal_port = 3012
  ports = []
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
